name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  version:
    name: Get version numbers
    uses: kuba2k2/kuba2k2/.github/workflows/version.yml@master
  lint-clang:
    name: Run Clang lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-clang.yml@master

  build-cmake-windows-x86_64:
    name: Build CMake project (windows-x86_64)
    needs:
      - version
      - lint-clang
    uses: kuba2k2/kuba2k2/.github/workflows/build-cmake.yml@master
    with:
      runs-on: windows-latest
      args: -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=MinSizeRel
      args-build: --config MinSizeRel
      cache-key: windows-x86_64
      pre-build: |
        git submodule update --init --recursive
      post-build: |
        cp cmake-build/src/MinSizeRel/zuzel.exe zuzel-v${{ needs.version.outputs.tag }}-windows-x86_64.exe
        cp cmake-build/src/MinSizeRel/zuzel-server.exe zuzel-server-v${{ needs.version.outputs.tag }}-windows-x86_64.exe
      files: zuzel*.exe
      output-artifact: cmake-build-windows-x86_64

  build-cmake-linux-x86_64:
    name: Build CMake project (linux-x86_64)
    needs:
      - version
      - lint-clang
    uses: kuba2k2/kuba2k2/.github/workflows/build-cmake.yml@master
    with:
      runs-on: ubuntu-latest
      runs-on-alpine: true
      alpine-packages: |
        git cmake make gcc musl-dev
        libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxi-dev libxkbcommon-dev libdrm-dev
      args: -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel
      args-build: --config MinSizeRel
      cache-key: linux-alpine-x86_64
      pre-build: |
        git submodule update --init --recursive
      post-build: |
        cp cmake-build/src/zuzel zuzel-v${{ needs.version.outputs.tag }}-linux-x86_64
        cp cmake-build/src/zuzel-server zuzel-server-v${{ needs.version.outputs.tag }}-linux-x86_64
      files: zuzel*
      output-artifact: cmake-build-linux-alpine-x86_64

  gh-release:
    name: Publish GitHub release
    needs:
      - version
      - build-cmake-windows-x86_64
      - build-cmake-linux-x86_64
    uses: kuba2k2/kuba2k2/.github/workflows/gh-release.yml@master
    permissions:
      contents: write
    with:
      artifact: cmake-build-*
      name: v${{ needs.version.outputs.tag }}
